# Generated by Django 4.1.1 on 2022-10-16 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.TextField(choices=[('AR', 'Array'), ('BI', 'Binary'), ('DP', 'Dynamic Programming'), ('GR', 'Graph'), ('IN', 'Interval'), ('LL', 'Linked List'), ('MX', 'Matrix'), ('ST', 'String'), ('TR', 'Tree'), ('HE', 'Heap')], max_length=255, unique=True)),
                ('last_done', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.ManyToManyField(to='beatcodeApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField()),
                ('problem', models.ManyToManyField(to='beatcodeApp.problem')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sub_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('mem_used', models.IntegerField()),
                ('success', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatcodeApp.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemToProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatcodeApp.problem')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatcodeApp.problemset')),
            ],
        ),
    ]
