# Generated by Django 4.0.2 on 2022-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcodeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField()),
                ('pid', models.ManyToManyField(to='beatcodeApp.Problem')),
                ('uid', models.ManyToManyField(to='beatcodeApp.User')),
            ],
        ),
    ]
