# Generated by Django 4.1.1 on 2022-10-22 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beatcodeApp", "0002_remove_problem_category_problem_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="problem",),
        migrations.RemoveField(model_name="todo", name="user",),
        migrations.AddField(
            model_name="todo",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beatcodeApp.problem",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
