# Generated by Django 4.0.2 on 2022-11-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatcodeApp', '0004_alter_problem_problem_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='progress',
        ),
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
