# Generated by Django 4.1.1 on 2022-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beatcodeApp", "0006_problem_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
