# Generated by Django 4.1.1 on 2022-12-05 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("beatcodeApp", "0010_problem_title_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
