# Generated by Django 4.1.1 on 2022-12-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beatcodeApp", "0011_alter_problem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="mem_used",
            field=models.FloatField(),
        ),
    ]
