# Generated by Django 4.0.2 on 2022-10-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
